<font color="green">To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.</font>

# Python Programming:  Simple Random Sampling


## Importing our Libraries

In [ ]:
# importing numpy
import numpy as np

# importing pandas
import pandas as pd

# importing random module
# we will use random.sample() function to return a k length 
# list of unique elements chosen from our population
import random

## 1.0 Selecting More than One item from a List

In [ ]:
# Example 1
# ---
# Selecting more than one item from a list 
# ---
#

list = [20, 40, 80, 100, 120]
print ("Choosing 3 random items from a list using sample function", random.sample(list, k=3))

list = [20, 40, 20, 20, 20]
print ("Choosing 3 random items from a list using sample function",random.sample(list, k=3))

# As you can see we pass k=3 to choose 3 random elements from a list. 
# In return, we got a list of 3 random items.

Choosing 3 random items from a list using sample function [80, 40, 100]
Choosing 3 random items from a list using sample function [20, 20, 40]


### <font color="green"> 1.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Create a list containing 10 counties in Kenya 
# then select 2 random counties from the list.
# ---
# 
counties = ['Nairobi','Kisumu','Mombasa','Kitale','Eldoret','Turkana','Isiolo',]

print("Choosing 3 counties: ", random.sample(counties, k=3))

Choosing 3 counties:  ['Nairobi', 'Kitale', 'Turkana']


## 2.0  Selecting the Random Sample from Dictionary

In [ ]:
# Example 1
# ---
# We can select a random key-value pair from the dictionary as shown 
# ---
#
marks_dict = {
  "Kelly": 55,
  "jhon": 70,
  "Donald": 60,
  "Lennin" :50
}

print ("Choosing 2 random items from a dictionary using sample method ", random.sample(marks_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('Donald', 60), ('jhon', 70)]


### <font color="green">2.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# A caterer offers three different food packages; 
# bronze package: starch:rice stew:chicken curry vegetable:cabbages desert:melon
# silver package: starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas
# gold package: starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart
# Create a dictionary that stores the above information and select a sample of size 2 
# ---
#


## 3.0 Selecting a Random Sample with Replacement to including repetition


In [ ]:
# Example 1
# ---
# We can select a random sample with replacement to include repetition as shown below
# ---
# 
names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]

print("random sample with replacement to including repetition ", random.choices(names, k=3))

random sample with replacement to including repetition  ['Andre', 'Nadal', 'Martina']


### <font color="green">3.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select a random sample of 3 with replacement to include replacement from the 
# following list of months
# ---
#

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']
print("with repetion on: ", random.choices(months,k=4))

with repetion on:  ['January', 'February', 'December', 'November']


## 4.0 Selecting a Random Sample from a Range of Integers

In [ ]:
# Example 1
# ---
# We can select a random sample from a range of integers as shown below
# ---
# 

weight_set = {40, 50, 55, 65, 75, 80}

print ("Choosing 4 random items from a set ", random.sample(weight_set, k=4))

Choosing 4 random items from a set  [40, 75, 55, 65]


### <font color="green">4.1 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select a random sample from a range of integers as shown below
# --- 
# 
weight_set = {4, 5, 6, 7, 8, 9, 10}

OUR CODE GOES HERE

## 5.0 Selecting a Sample Array from a Large multidimensional Array



In [ ]:
# Example 1
# ---
# We can select a sample array from a large multidimensional array as shown
# ---
# 

array = np.array([[2 ,4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]]) 
print("\n =============== Printing 2D Array =================")
print(array)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)
for i in randomRows:
  print(array[i,:])


 =============== Printing 2D Array =================
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Selecting multiple random rows from the 2D array
[ 6 12 18]
[ 5 10 15]


### <font color="green">5.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select two arrays from the given multidimensional array
# ---
# 

a = [[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [1 ,2 , 4, 5, 6], [5, 10, 15, 20, 25], [6, 12, 18, 24, 30], [7, 14, 21, 28, 35]]  

r_rows = np.random.randint(7,size=2)

for i in r_rows:
  print(a[i,:])

TypeError: ignored

## 6.0 Selecting Random Samples from a Dataset

In [ ]:
# Example 1
# ---
# Selecting a random sample from the following medical appointments dataset
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
# 

# Loading the dataset
medical_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")

# Determining the size
print(medical_df.shape)


# Previewing the dataset
print(medical_df.head())

# Selecting the sample 
medical_sample = medical_df.sample(n = 10, replace="False")
print("\n =========== sample =============\n ")
print(medical_sample)

(110527, 14)
      PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No
3  8.679512e+11        5642828      F  ...       0            0       No
4  8.841186e+12        5642494      F  ...       0            0       No

[5 rows x 14 columns]

 =========== sample =============
 
           PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
61582   2.519584e+13        5696082      F  ...       0            1      Yes
18351   1.842445e+14        5731525      M  ...       0            0       No
93283   7.128416e+12        5770073      F  ...       0            0       No
87059   6.387756e+13        5537583      M  ...       0            1       No
82185   1.616819e+13        5594722      M  ...       0            0      Yes
109728  5.931188e+12 

### <font color="green">6.0 Challenges </font>

In [ ]:
# Challenge 1
# ---
# Select a random sample of 10 from the given dataset below 
# ---
# Dataset url = http://bit.ly/DSRussianInvestigation
# ---
url = "http://bit.ly/DSRussianInvestigation"

dt = pd.read_csv(url)
print(dt.columns)
print(dt.shape,"\n")
print(dt.sample(n=10, replace="False"))

Index(['investigation', 'investigation-start', 'investigation-end',
       'investigation-days', 'name', 'indictment-days ', 'type', 'cp-date',
       'cp-days', 'overturned', 'pardoned', 'american', 'president'],
      dtype='object')
(194, 13) 

                     investigation  ...         president
94   sealed-investigation-hwbush-1  ...  George H.W. Bush
90                     iran-contra  ...     Ronald Reagan
82                     iran-contra  ...     Ronald Reagan
66                       watergate  ...     Richard Nixon
92                     iran-contra  ...     Ronald Reagan
77                          deaver  ...     Ronald Reagan
173                         russia  ...      Donald Trump
167                         russia  ...      Donald Trump
7                        watergate  ...     Richard Nixon
128                     whitewater  ...      Bill Clinton

[10 rows x 13 columns]


In [ ]:
# Challenge 2
# ---
# A medical company would like to follow up with 50 patients who never showed up for appointments 
# but received an sms. Select a random sample from such patients given the medical dataset below 
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
#
OUR CODE GOES HERE